"use client";
import Link from "next/link";
import { ArrowRight, Check, ChevronRight, Clock3, Dumbbell, Flame, MapPin, Play, Zap } from "lucide-react";
import { useEffect, useState } from "react";
import { currentQuery, useCademiUser } from "@/lib/cademi";
import { appConfig, placeLabels, TrainingPlace, week, workouts } from "@/lib/config";
import { AppShell } from "./app-shell";
const places: { id: TrainingPlace; icon: typeof Dumbbell; sub: string }[] = [{ id: "gym", icon: Dumbbell, sub: "Equipamento completo" }, { id: "home", icon: MapPin, sub: "Com pouco material" }, { id: "express", icon: Zap, sub: "Versão rápida" }];
export function Dashboard() { const user = useCademiUser(); const workout = workouts["peito-triceps"]; const [place, setPlace] = useState<TrainingPlace>("gym"); const [complete, setComplete] = useState(false); useEffect(() => { const saved = localStorage.getItem("samora-workout:place") as TrainingPlace | null; if (saved && placeLabels[saved]) setPlace(saved); setComplete(localStorage.getItem(`samora-workout:day-${workout.day}`) === "done"); }, [workout.day]); const choosePlace = (next: TrainingPlace) => { setPlace(next); localStorage.setItem("samora-workout:place", next); }; const progress = complete ? 41 : appConfig.defaults.progress;
return <AppShell><section className="welcome"><p>BEM-VINDO DE VOLTA</p><h1>Olá, {user.firstName}.<br /><span>Vamos treinar?</span></h1></section><section className="hero-card"><img src={workout.image} alt="Bruno Samora com halteres" /><div className="hero-overlay" /><div className="hero-copy"><div className="day-chip"><Flame size={15} /> DIA {workout.day} · {workout.eyebrow}</div><h2>{workout.title}</h2><div className="meta"><span><Clock3 />{workout.duration}</span><span><Dumbbell />{workout.level}</span></div><Link className="primary-button" href={`/workout/${workout.slug}${currentQuery()}`}>{complete ? "REVER TREINO" : "COMEÇAR TREINO"}<ArrowRight /></Link></div></section><section className="section-block"><div className="section-heading"><div><p>ADAPTA AO TEU DIA</p><h2>Onde vais treinar?</h2></div><span>{placeLabels[place]}</span></div><div className="place-grid">{places.map(({ id, icon: Icon, sub }) => <button key={id} onClick={() => choosePlace(id)} className={place === id ? "place-card selected" : "place-card"}><Icon /><strong>{placeLabels[id]}</strong><small>{sub}</small>{place === id && <i><Check /></i>}</button>)}</div></section><section className="section-block"><div className="section-heading"><div><p>SEMANA ACTUAL</p><h2>Continua em movimento.</h2></div><strong className="streak">2 <Flame /> dias</strong></div><div className="week-grid">{week.map((item) => <div key={item.day} className={`week-day ${item.state}`}><span>{item.day}</span><i>{item.state === "done" ? <Check /> : item.day.slice(0, 1)}</i><small>{item.label}</small></div>)}</div></section><section id="progresso" className="progress-card"><div className="progress-number"><strong>{progress}%</strong><span>DO PROGRAMA</span></div><div className="progress-copy"><p>O teu progresso</p><h2>{complete ? "13" : "12"} de 30 treinos</h2><div className="progress-track"><span style={{ width: `${progress}%` }} /></div><small>Cada treino conta. Mantém o ritmo.</small></div></section><section className="continue-card"><img src="/images/workout-bruno.jpg" alt="Bruno Samora no ginásio" /><div><p>CONTINUA ONDE PARASTE</p><h2>Aquecimento e técnica</h2><span>Vídeo · 08 min</span></div><button aria-label="Continuar"><Play fill="currentColor" /></button></section><section id="recomendados" className="section-block recommendations"><div className="section-heading"><div><p>PARA COMPLETAR</p><h2>Recomendado para ti</h2></div></div><div className="recommend-grid"><article><span className="mini-icon"><Flame /></span><div><strong>Mobilidade de ombros</strong><small>Preparação · 7 min</small></div><ChevronRight /></article><article><span className="mini-icon"><Dumbbell /></span><div><strong>Core essencial</strong><small>Complementar · 12 min</small></div><ChevronRight /></article></div></section><section id="apoio" className="support-strip"><span>Precisas de ajuda com o treino?</span><a href={appConfig.cademi.support}>Falar com o apoio <ArrowRight /></a></section></AppShell>; }
