"use client";
import Link from "next/link";
import { ArrowLeft, Check, ChevronRight, Clock3, Dumbbell, ExternalLink, Trophy } from "lucide-react";
import { useEffect, useState } from "react";
import { currentQuery } from "@/lib/cademi";
import { placeLabels, TrainingPlace, workouts } from "@/lib/config";
import { AppShell } from "./app-shell";
export function WorkoutDetail() { const workout = workouts["peito-triceps"]; const [place, setPlace] = useState<TrainingPlace>("gym"); const [done, setDone] = useState(false); useEffect(() => { const p = localStorage.getItem("samora-workout:place") as TrainingPlace | null; if (p && placeLabels[p]) setPlace(p); setDone(localStorage.getItem(`samora-workout:day-${workout.day}`) === "done"); }, [workout.day]); const finish = () => { localStorage.setItem(`samora-workout:day-${workout.day}`, "done"); setDone(true); window.scrollTo({ top: 0, behavior: "smooth" }); };
return <AppShell active="workout"><div className="workout-top"><Link href={`/dashboard${currentQuery()}`}><ArrowLeft /> Voltar</Link><span>DIA {workout.day} DE 30</span></div><section className={done ? "completion-banner visible" : "completion-banner"}><Trophy /><div><strong>Treino concluído!</strong><span>Mais um passo na tua evolução.</span></div></section><section className="workout-title"><p>{workout.eyebrow}</p><h1>{workout.title}</h1><div className="meta"><span><Clock3 />{workout.duration}</span><span><Dbell />{workout.level}</span></div></section><div className="variant-tabs" role="tablist">{(Object.keys(placeLabels) as TrainingPlace[]).map((p) => <button key={p} onClick={() => { setPlace(p); localStorage.setItem("samora-workout:place", p); }} className={p === place ? "active" : ""}>{placeLabels[p]}</button>)}</div><section className="exercise-list">{workout.exercises[place].map((exercise, index) => <article key={exercise[0]}><span className="exercise-index">{String(index + 1).padStart(2, "0")}</span><div><h2>{exercise[0]}</h2><p>{exercise[1]}</p><a href="#execucao">Ver execução <ExternalLink /></a></div><button aria-label={`Marcar ${exercise[0]} como concluído`}><Check /></button></article>)}</section><button className={done ? "finish-button done" : "finish-button"} onClick={finish}>{done ? <><Check /> TREINO CONCLUÍDO</> : "FINALIZAR TREINO"}</button><section className="next-workout"><div><p>PRÓXIMO TREINO</p><h2>{workout.next}</h2><span>Dia 13 · 50 min</span></div><ChevronRight /></section><p className="workout-note">O progresso é guardado neste dispositivo. Os dados recebidos pela URL servem apenas para personalizar a experiência.</p></AppShell>; }
function Dbell(){return <Dumbbell />}
